# config.py
import argparse

args = argparse.Namespace(
    num_IRK_stages=100,
    log_dir="./risultati/",
    no_cuda=False,
    gpu_number=0,
    num_train=1000,
    num_val=200,
    num_test=400,
    num_plot=1,
    use_scheduler=False,
    scheduler_type="plateau",
    patience=2000,
    factor=0.8,
    use_tqdm=False,
    lr=1e-3,
    epochs=50000,
    state_dim=12,
    alg_state_dim=11,
    input_state_dim=5,
    batch_size=100,
    test_every=1000,
    start_from_best=False,
    model_name="no-name",
    dropout_rate=0.0,
    dyn_bn="no-bn",
    dyn_ln="no-ln",
    dyn_type="attention",
    unstacked=True,#False,
    use_input_layer=False,
    dyn_width=100,
    dyn_depth=5,
    dyn_activation="sin",
    dyn_weight=1.0,
    alg_bn="no-bn",
    alg_ln="no-ln",
    alg_type="attention",
    alg_width=40,
    alg_depth=2,
    alg_activation="sin",
    alg_weight=1.0,
    h=0.25,
    N=10,
    method="BDF"
)
